# Generated by Django 3.2.7 on 2021-12-02 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customers',
            new_name='Customer',
        ),
        migrations.RenameModel(
            old_name='CustomerGroups',
            new_name='CustomerGroup',
        ),
    ]
